const dataKeyboard = [
  {
    en: '`',
    ru: 'ё',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '1',
    ru: '1',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '2',
    ru: '2',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '3',
    ru: '3',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '4',
    ru: '4',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '5',
    ru: '5',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '6',
    ru: '6',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '7',
    ru: '7',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '8',
    ru: '8',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '9',
    ru: '9',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '0',
    ru: '0',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '-',
    ru: '_',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '=',
    ru: '+',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    keySystem: 'Backspace',
    en: 'Backspace',
    ru: 'Backspace',
    class: ['keyboard__btn', 'keyboard__btn_size_m-right', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    keySystem: 'Tab',
    en: 'Tab',
    ru: 'Tab',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    en: 'q',
    ru: 'й',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'w',
    ru: 'ц',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'e',
    ru: 'у',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'r',
    ru: 'к',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 't',
    ru: 'е',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'y',
    ru: 'н',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'u',
    ru: 'г',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'i',
    ru: 'ш',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'o',
    ru: 'щ',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'p',
    ru: 'з',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '[',
    ru: 'х',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: ']',
    ru: 'ъ',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '|',
    ru: '/',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    keySystem: 'Delete',
    en: 'Del',
    ru: 'Del',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    keySystem: 'CapsLock',
    en: 'Caps Lock',
    ru: 'Caps Lock',
    class: ['keyboard__btn', 'keyboard__btn_size_m-left', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    en: 'a',
    ru: 'ф',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 's',
    ru: 'ы',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'd',
    ru: 'в',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'f',
    ru: 'а',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'g',
    ru: 'п',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'h',
    ru: 'р',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'j',
    ru: 'о',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'k',
    ru: 'л',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'l',
    ru: 'д',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: ';',
    ru: 'ж',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '\'',
    ru: 'э',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    keySystem: 'Enter',
    en: 'Enter',
    ru: 'Enter',
    class: ['keyboard__btn', 'keyboard__btn_size_m-right', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    keySystem: 'Shift',
    en: 'Shift',
    ru: 'Shift',
    class: ['keyboard__btn', 'keyboard__btn_size_m-left', 'keyboard__btn_type_command', 'shift'],
    isSystem: true,
  },
  {
    en: '\\',
    ru: '\\',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'z',
    ru: 'я',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'x',
    ru: 'ч',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'c',
    ru: 'с',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'v',
    ru: 'м',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'b',
    ru: 'и',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'n',
    ru: 'т',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: 'm',
    ru: 'ь',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: ',',
    ru: 'б',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '.',
    ru: 'ю',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    en: '/',
    ru: '.',
    class: ['keyboard__btn'],
    isSystem: false,
  },
  {
    keySystem: 'ArrowUp',
    en: '⮝',
    ru: '⮝',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    keySystem: 'Shift',
    en: 'Shift',
    ru: 'Shift',
    class: ['keyboard__btn', 'keyboard__btn_type_command', 'shift'],
    isSystem: true,
  },
  {
    keySystem: 'Control',
    en: 'Ctrl',
    ru: 'Ctrl',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    keySystem: 'Meta',
    en: 'Win',
    ru: 'Win',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    keySystem: '',
    en: 'Alt',
    ru: 'Alt',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    en: ' ',
    ru: ' ',
    class: ['keyboard__btn', 'keyboard__btn_type_space'],
    isSystem: false,
  },
  {
    keySystem: '',
    en: 'Alt',
    ru: 'Alt',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    keySystem: 'Control',
    en: 'Ctrl',
    ru: 'Ctrl',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    keySystem: 'ArrowLeft',
    en: '⮜',
    ru: '⮜',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    keySystem: 'ArrowDown',
    en: '⮟',
    ru: '⮟',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
  },
  {
    keySystem: 'ArrowRight',
    en: '⮞',
    ru: '⮞',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
  },
]

export default dataKeyboard;
