const dataKeyboard = [
  {
    en: '`',
    ru: 'ё',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Backquote',
  },
  {
    en: '1',
    ru: '1',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Digit1',
  },
  {
    en: '2',
    ru: '2',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Digit2',
  },
  {
    en: '3',
    ru: '3',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Digit3',
  },
  {
    en: '4',
    ru: '4',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Digit4',
  },
  {
    en: '5',
    ru: '5',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Digit5',
  },
  {
    en: '6',
    ru: '6',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Digit6',
  },
  {
    en: '7',
    ru: '7',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Digit7',
  },
  {
    en: '8',
    ru: '8',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Digit8',
  },
  {
    en: '9',
    ru: '9',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Digit9',
  },
  {
    en: '0',
    ru: '0',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Digit0',
  },
  {
    en: '-',
    ru: '_',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Minus',
  },
  {
    en: '=',
    ru: '+',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Equal',
  },
  {
    keySystem: 'Backspace',
    en: 'Backspace',
    ru: 'Backspace',
    class: ['keyboard__btn', 'keyboard__btn_size_m-right', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'Backspace',
  },
  {
    keySystem: 'Tab',
    en: 'Tab',
    ru: 'Tab',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'Tab',
  },
  {
    en: 'q',
    ru: 'й',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyQ',
  },
  {
    en: 'w',
    ru: 'ц',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyW',
  },
  {
    en: 'e',
    ru: 'у',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyE',
  },
  {
    en: 'r',
    ru: 'к',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyR',
  },
  {
    en: 't',
    ru: 'е',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyT',
  },
  {
    en: 'y',
    ru: 'н',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyY',
  },
  {
    en: 'u',
    ru: 'г',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyU',
  },
  {
    en: 'i',
    ru: 'ш',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyI',
  },
  {
    en: 'o',
    ru: 'щ',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyO',
  },
  {
    en: 'p',
    ru: 'з',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyP',
  },
  {
    en: '[',
    ru: 'х',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'BracketLeft',
  },
  {
    en: ']',
    ru: 'ъ',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'BracketRight',
  },
  {
    en: '|',
    ru: '/',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Backslash',
  },
  {
    keySystem: 'Delete',
    en: 'Del',
    ru: 'Del',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'Delete',
  },
  {
    keySystem: 'CapsLock',
    en: 'Caps Lock',
    ru: 'Caps Lock',
    class: ['keyboard__btn', 'keyboard__btn_size_m-left', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'CapsLock',
  },
  {
    en: 'a',
    ru: 'ф',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyA',
  },
  {
    en: 's',
    ru: 'ы',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyS',
  },
  {
    en: 'd',
    ru: 'в',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyD',
  },
  {
    en: 'f',
    ru: 'а',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyF',
  },
  {
    en: 'g',
    ru: 'п',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyG',
  },
  {
    en: 'h',
    ru: 'р',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyH',
  },
  {
    en: 'j',
    ru: 'о',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyJ',
  },
  {
    en: 'k',
    ru: 'л',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyK',
  },
  {
    en: 'l',
    ru: 'д',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyL',
  },
  {
    en: ';',
    ru: 'ж',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Semicolon',
  },
  {
    en: '\'',
    ru: 'э',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Quote',
  },
  {
    keySystem: 'Enter',
    en: 'Enter',
    ru: 'Enter',
    class: ['keyboard__btn', 'keyboard__btn_size_m-right', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'Enter',
  },
  {
    keySystem: 'Shift',
    en: 'Shift',
    ru: 'Shift',
    class: ['keyboard__btn', 'keyboard__btn_size_m-left', 'keyboard__btn_type_command', 'shift'],
    isSystem: true,
    keyCode: 'ShiftLeft',
  },
  {
    en: '\\',
    ru: '\\',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Slash',
  },
  {
    en: 'z',
    ru: 'я',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyZ',
  },
  {
    en: 'x',
    ru: 'ч',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyX',
  },
  {
    en: 'c',
    ru: 'с',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyC',
  },
  {
    en: 'v',
    ru: 'м',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyV',
  },
  {
    en: 'b',
    ru: 'и',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyB',
  },
  {
    en: 'n',
    ru: 'т',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyN',
  },
  {
    en: 'm',
    ru: 'ь',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'KeyM',
  },
  {
    en: ',',
    ru: 'б',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Comma',
  },
  {
    en: '.',
    ru: 'ю',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Period',
  },
  {
    en: '/',
    ru: '.',
    class: ['keyboard__btn'],
    isSystem: false,
    keyCode: 'Period',
  },
  {
    keySystem: 'ArrowUp',
    en: '⮝',
    ru: '⮝',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'ArrowUp',
  },
  {
    keySystem: 'Shift',
    en: 'Shift',
    ru: 'Shift',
    class: ['keyboard__btn', 'keyboard__btn_type_command', 'shift'],
    isSystem: true,
    keyCode: 'ShiftRight',
  },
  {
    keySystem: 'Control',
    en: 'Ctrl',
    ru: 'Ctrl',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'ControlLeft',
  },
  {
    keySystem: 'Meta',
    en: 'Win',
    ru: 'Win',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'MetaLeft',
  },
  {
    keySystem: '',
    en: 'Alt',
    ru: 'Alt',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'AltLeft',
  },
  {
    en: ' ',
    ru: ' ',
    class: ['keyboard__btn', 'keyboard__btn_type_space'],
    isSystem: false,
    keyCode: 'Space',
  },
  {
    keySystem: '',
    en: 'Alt',
    ru: 'Alt',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'AltRight',
  },
  {
    keySystem: 'Control',
    en: 'Ctrl',
    ru: 'Ctrl',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'ControlRight',
  },
  {
    keySystem: 'ArrowLeft',
    en: '⮜',
    ru: '⮜',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'ArrowLeft',
  },
  {
    keySystem: 'ArrowDown',
    en: '⮟',
    ru: '⮟',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'ArrowDown',
  },
  {
    keySystem: 'ArrowRight',
    en: '⮞',
    ru: '⮞',
    class: ['keyboard__btn', 'keyboard__btn_type_command'],
    isSystem: true,
    keyCode: 'ArrowRight',
  },
];

export default dataKeyboard;
